### ISSUE TITLE
Add image

### ISSUE THREAD

**Issue by jordicapellad3s** [jordicapedo/jordicapedo#1]
![Jordi Capellades](https://user-images.githubusercontent.com/65649227/131827774-3e70fb70-b6c6-486e-a7ad-70fd343ddcaa.png)

**Comment by jordicapellad3s** [comment]
![Jordi Capellades (2)](https://user-images.githubusercontent.com/65649227/131835269-93fcde3a-6e74-4048-a631-8084a9a70e12.png)

**Comment by jordicapedo** [comment]
![Jordi Capellades (4)](https://user-images.githubusercontent.com/65649227/131850946-abad9fb3-b5f3-49ea-91e4-b1835c341aad.png)

**Comment by jordicapedo** [comment]
![Jordi Capellades (5)](https://user-images.githubusercontent.com/65649227/131851550-93793f27-b3c0-4b39-a0fb-ddf91c9cf3bc.png)

**Comment by jordicapedo** [comment]
![github-readme](https://user-images.githubusercontent.com/65649227/131967166-51f9948b-ade8-4a22-87e8-19b72ba4b581.png)

**Comment by jordicapellad3s** [comment]
![github-readme](https://user-images.githubusercontent.com/65649227/131967191-9e54f65c-e432-4190-b300-67b6921e966e.png)

**Comment by jordicapellad3s** [comment]
not image needed
